POST http://localhost:8080/user/create
Content-Type: application/json

{
  "username": "John Doe",
  "password": "password",
  "email": "johna@email.com"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json


{
  "email": "johna@email.com",
  "password": "password"
}


###

GET http://localhost:8080/user/9caff085-0649-405b-8c16-886436ccdf97


### 

POST http://localhost:8080/review/create
Content-Type: application/json

{
  "content": "This is a great movie",
  "rating": 5,
  "userId": "9caff085-0649-405b-8c16-886436ccdf9",
  "movieId": 112234,
  "title": "Inside Out 2",
  "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  "release_date": "2024-06-11",
  "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg"

}
###

PUT http://localhost:8080/user/add/favorites
Content-Type: application/json

{
  "userId": "9caff085-0649-405b-8c16-886436ccdf97",
  "movieId": 11224,
  "title": "Inside Out 2",
  "overview": "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
  "release_date": "2024-06-11",
  "poster_path": "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg"
}

###
PUT http://localhost:8080/user/remove/favorites
Content-Type: application/json

{
  "userId": "9caff085-0649-405b-8c16-886436ccdf97",
  "movieId": 11224
}